SELECT * FROM indice;

CREATE FUNCTION PreencherIDX ()
RETURNS void
LANGUAGE SQL
AS $$
	UPDATE Indice
	SET IDX = ((IDH_EDUCACAO * IDH_EDUCACAO) * IDH_LONGEVIDADE)/IDH_GERAL
$$;

SELECT PreencherIDX();
SELECT * FROM indice;
